config/routes.rb
Rails.application.routes.draw do

  root 'crawler#new'
  post 'crawler' =>   'crawler#create'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crawler_controller.rb
class CrawlerController < ApplicationController
  
  def new
  end

  def create
    crawler = crawler_params
    redirect_to root_url if crawler[:site].empty?
    crawl!(crawler)
  end
  
    private

    #Add http/s prefix if not present
    def setting_url(url)
      unless url.start_with?("http://", "https://")
        url = "http://" + url 
      else
        url
      end
     # url.insert(7, "www.") unless url.include?("www.")
     # url
    end
      
    #Crawling the site
    def crawl!(crawler)
      @links = {}
      url = setting_url(crawler[:site])
      depth = crawler[:deep].to_i
      Anemone.crawl(url, 
                    :discard_page_bodies => true, 
                    :depth_limit=>depth) do |anemone|
                      anemone.on_every_page do |page|
                      @links[page.url] = page.referer
                    end
      end
    end

    #Accept only this params
    def crawler_params
      params.require(:crawler).permit(:site, :deep)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crawler_helper.rb
module CrawlerHelper
end

app/views/crawler/create.html.erb
<h1>Your result map: (Referer --> Sub_url)</h1>
<% @links.each do |link, referer| %>
    <br />
    <%= referer %><br>
    |<br>
    |-----> <%= link %><br>
    
<% end %>

app/views/crawler/new.html.erb
<h1>Welcome to my Really Simple Crawler</h1>
<%= form_for(:crawler, url: crawler_path) do |f| %>

      <%= f.label :site %>
      <%= f.text_field :site, placeholder: "stackoverflow.com" %>

      <%= f.label :depth %>
      <%= f.select :deep, (1..5) %>

      <%= f.submit "Map it!" %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReallySimpleCrawler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>